"""Canonical auth services package boundary."""

from .auth_service import AuthService, Session, UserAccount, UserRole, UserStatus
from .authorization_service import (
    AuthorizationConfig,
    AuthorizationService,
    Policy,
    PolicyEnforcementResult,
    PolicyType,
)
from .config import INSECURE_SECRET_MARKERS, AuthConfig, Environment, load_auth_config
from .data_protection_service import (
    DataProtectionConfig,
    DataProtectionPolicy,
    DataProtectionResult,
    DataProtectionService,
    DataSensitivity,
    EncryptionAlgorithm,
    EncryptionKey,
    RetentionPolicy,
)
from .tenant_isolation import (
    CrossTenantAccessError,
    SecurityIncident,
    SecurityIncidentLogger,
    SecurityIncidentType,
    TenantAccessLevel,
    TenantContext,
    TenantIsolationError,
    TenantIsolationService,
    TenantValidator,
    VectorStoreTenantFilter,
    create_tenant_context,
    get_tenant_isolation_service,
    validate_tenant_access,
)
from .user_service import (
    TenantNotFoundError,
    UserAlreadyExistsError,
    UserNotFoundError,
    UserService,
    UserServiceError,
)

__all__ = [
    "INSECURE_SECRET_MARKERS",
    "AuthConfig",
    "AuthService",
    "AuthorizationConfig",
    "AuthorizationService",
    "CrossTenantAccessError",
    "DataProtectionConfig",
    "DataProtectionPolicy",
    "DataProtectionResult",
    "DataProtectionService",
    "DataSensitivity",
    "EncryptionAlgorithm",
    "EncryptionKey",
    "Environment",
    "Policy",
    "PolicyEnforcementResult",
    "PolicyType",
    "RetentionPolicy",
    "SecurityIncident",
    "SecurityIncidentLogger",
    "SecurityIncidentType",
    "Session",
    "TenantAccessLevel",
    "TenantContext",
    "TenantIsolationError",
    "TenantIsolationService",
    "TenantNotFoundError",
    "TenantValidator",
    "UserAccount",
    "UserAlreadyExistsError",
    "UserNotFoundError",
    "UserRole",
    "UserService",
    "UserServiceError",
    "UserStatus",
    "VectorStoreTenantFilter",
    "create_tenant_context",
    "get_tenant_isolation_service",
    "load_auth_config",
    "validate_tenant_access",
]
