"""
AI-Karen Personalization Goals Module.

Exports cognitive contracts for goals, intentions, commitments, and
prospective memory.
"""

from __future__ import annotations

from .contracts import (
    Commitment,
    CommitmentCondition,
    CommitmentEvidence,
    CommitmentParty,
    CommitmentSource,
    CommitmentStatus,
    CommitmentStrength,
    CompletionEvidenceSource,
    ConflictSeverity,
    ConflictType,
    EvidenceSourceType,
    Goal,
    GoalConflict,
    GoalEvidence,
    GoalId,
    GoalOrigin,
    GoalOutcome,
    GoalPriority,
    GoalPriorityAssessment,
    GoalProgress,
    GoalRevision,
    GoalSnapshot,
    GoalState,
    GoalType,
    Intention,
    IntentionEvidence,
    IntentionPriority,
    IntentionState,
    IntentionTriggerType,
    ProspectiveMemory,
    ProspectiveState,
    ProspectiveTrigger,
    UserGoal,
    UserGoalStatus,
    goal_from_user_goal,
    to_snapshot,
)
from .lifecycle import (
    GoalLifecycle,
    GoalStore,
)
from .conflicts import ConflictDetector
from .prioritization import GoalPrioritizer
from .prospective import (
    CommitmentLifecycle,
    IntentionLifecycle,
    ProspectiveMemoryManager,
    make_commitment_evidence,
    make_commitment_id,
    make_intention_id,
    make_pm_id,
)

__all__ = [
    "Commitment",
    "CommitmentCondition",
    "CommitmentEvidence",
    "CommitmentLifecycle",
    "CommitmentParty",
    "CommitmentSource",
    "CommitmentStatus",
    "CommitmentStrength",
    "CompletionEvidenceSource",
    "ConflictDetector",
    "ConflictSeverity",
    "ConflictType",
    "EvidenceSourceType",
    "Goal",
    "GoalConflict",
    "GoalEvidence",
    "GoalId",
    "GoalLifecycle",
    "GoalOrigin",
    "GoalOutcome",
    "GoalPriority",
    "GoalPriorityAssessment",
    "GoalProgress",
    "GoalPrioritizer",
    "GoalRevision",
    "GoalSnapshot",
    "GoalState",
    "GoalStore",
    "GoalType",
    "Intention",
    "IntentionEvidence",
    "IntentionLifecycle",
    "IntentionPriority",
    "IntentionState",
    "IntentionTriggerType",
    "ProspectiveMemory",
    "ProspectiveMemoryManager",
    "ProspectiveState",
    "ProspectiveTrigger",
    "UserGoal",
    "UserGoalStatus",
    "goal_from_user_goal",
    "make_commitment_evidence",
    "make_commitment_id",
    "make_intention_id",
    "make_pm_id",
    "to_snapshot",
]
