from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional
from enum import Enum
from uuid import uuid4

class StepStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"

@dataclass
class PlanStep:
    """A single step in the DeepExecutionPlan"""
    id: str = field(default_factory=lambda: str(uuid4()))
    description: str = ""
    agent_specialist: str = ""  # e.g., "researcher", "coder", "analyst"
    agent_version: Optional[str] = None  # pinned registration version for reproducibility
    input_data: Dict[str, Any] = field(default_factory=dict)
    dependencies: List[str] = field(default_factory=list) # IDs of steps that must finish first
    status: StepStatus = StepStatus.PENDING
    output_data: Optional[Dict[str, Any]] = None
    error: Optional[str] = None

    # Authorized side-effect surface for this step (validated pre-execution)
    required_tools: List[str] = field(default_factory=list)
    required_plugins: List[str] = field(default_factory=list)

    # Prompt contract the specialist must load for this step (A10 / reproducibility)
    prompt_contract_id: Optional[str] = None
    prompt_version: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "description": self.description,
            "agent_specialist": self.agent_specialist,
            "agent_version": self.agent_version,
            "input_data": self.input_data,
            "dependencies": self.dependencies,
            "status": self.status.value,
            "output_data": self.output_data,
            "error": self.error,
            "required_tools": self.required_tools,
            "required_plugins": self.required_plugins,
            "prompt_contract_id": self.prompt_contract_id,
            "prompt_version": self.prompt_version,
        }

@dataclass
class DeepExecutionPlan:
    """The full execution plan generated by the Medusa Coordinator"""
    request_id: str
    steps: List[PlanStep] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    is_complete: bool = False
    
    def get_next_runnable_steps(self) -> List[PlanStep]:
        """Returns steps that have no pending dependencies"""
        completed_step_ids = {step.id for step in self.steps if step.status == StepStatus.COMPLETED}
        return [
            step for step in self.steps 
            if step.status == StepStatus.PENDING 
            and all(dep_id in completed_step_ids for dep_id in step.dependencies)
        ]
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "request_id": self.request_id,
            "steps": [step.to_dict() for step in self.steps],
            "metadata": self.metadata,
            "is_complete": self.is_complete
        }
