"""Contract tests for the actual SQL generated by governed profile recall.

These tests validate PostgreSQL query shape without pretending to exercise
a live database. Integration read-after-write must run with PostgreSQL.
"""

import uuid
from contextlib import asynccontextmanager
from types import SimpleNamespace

import pytest
from sqlalchemy.dialects import postgresql

from ai_karen_engine.platform.memory.postgres import profile_retriever


class _Result:
    def scalars(self):
        return self

    def all(self):
        return []


class _Session:
    def __init__(self):
        self.statement = None

    async def execute(self, statement):
        self.statement = statement
        return _Result()


@pytest.mark.asyncio
async def test_name_recall_sql_scopes_consent_active_facts_and_target(monkeypatch):
    tenant_id, user_id = uuid.uuid4(), uuid.uuid4()
    session = _Session()
    scope = []

    @asynccontextmanager
    async def scoped_session(*, tenant_id):
        scope.append(tenant_id)
        yield session

    monkeypatch.setattr(
        profile_retriever, "async_transaction_scope", scoped_session
    )
    query = SimpleNamespace(
        text="What's my name?",
        tenant_id=str(tenant_id),
        user_id=str(user_id),
        top_k=1,
    )
    assert await profile_retriever.PostgresProfileRecallRetriever().recall(query) == []
    assert scope == [str(tenant_id)]

    compiled = session.statement.compile(dialect=postgresql.dialect())
    statement = str(compiled).lower()
    values = list(compiled.params.values())
    assert "join" in statement
    assert "memory_events" in statement or "memory_event" in statement
    assert "profile_facts" in statement or "profile_fact" in statement
    assert "consent_state" in statement
    assert "valid_to is null" in statement.replace("profile_facts.", "").replace("profile_fact.", "")
    assert str(tenant_id) not in statement
    assert "granted" in values
    assert "preferred_name" in values
    assert tenant_id in values
    assert user_id in values
    assert 1 in values


@pytest.mark.asyncio
async def test_profile_recall_invalid_identity_does_not_query_database(monkeypatch):
    @asynccontextmanager
    async def no_db(*, tenant_id):
        pytest.fail("Database should not be queried for invalid scope")
        yield

    monkeypatch.setattr(profile_retriever, "async_transaction_scope", no_db)
    query = SimpleNamespace(
        text="What's my name?",
        tenant_id="not-a-uuid",
        user_id="not-a-uuid",
        top_k=1,
    )
    assert await profile_retriever.PostgresProfileRecallRetriever().recall(query) == []
