#!/bin/bash
# AI-Karen Docker Startup Script
# Generated by setup_environment.py

echo "🚀 Starting AI-Karen Docker Services"
echo "=" * 40

# Export environment variables
export REDIS_PASSWORD="JEmvDv4I17iRY2lJbmWuJOkL"
export POSTGRES_PASSWORD="karen_secure_pass_change_me"
export MINIO_ACCESS_KEY="karen_minio_user"
export MINIO_SECRET_KEY="D128S7ylydJn4TxvpbIhSbKkW7M"

# Stop any existing services
echo "🛑 Stopping existing services..."
docker compose down

# Start services in order
echo "🔄 Starting infrastructure services..."
docker compose up -d postgres redis elasticsearch minio

# Wait for services to be ready
echo "⏳ Waiting for services to be ready..."
sleep 30

# Start remaining services
echo "🔄 Starting application services..."
docker compose up -d

# Show status
echo "📊 Service Status:"
docker compose ps

echo ""
echo "✅ AI-Karen services started!"
echo "🌐 Frontend: http://localhost:8010"
echo "🔗 Backend API: http://localhost:8000"
echo "📊 Grafana: http://localhost:3001"
echo "📈 Prometheus: http://localhost:9090"
echo "🗄️  MinIO: http://localhost:9000"
